config/routes.rb
Rethinkfilms::Application.routes.draw do
  resources :companies

  resources :people

  resources :distributors

  resources :productions

  get "technology/index"
  resources :items

  root :to => "items#index"

end

app/models/cast.rb
class Cast
  include NoBrainer::Document

  field :name
  field :character
  field :picture

  belongs_to :item

end

app/models/company.rb
class Company
  include NoBrainer::Document

  belongs_to :item

end

app/models/director.rb
class Director
  include NoBrainer::Document

  field :name

end

app/models/distributor.rb
class Distributor
  # To change this template use File | Settings | File Templates.
end

app/models/item.rb
class Item
  include NoBrainer::Document

  # Defines the fields of the document visible to the application
  field :title
  field :title_original
  field :type, :default => "film"
  field :description
  field :year
  field :poster
  field :bg_image
  field :countries #, :type => Array
  field :persons
  field :companies

  #has_many :releases
  #has_many :poster
  has_many :persons
  #has_many :companies

  #serialize :persons, Array

  #<a class="th [radius]" href="#">
  #<img src="http://ia.media-imdb.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SY317_CR1,0,214,317_AL_.jpg">
  #</a>
  #              <%= form_for @item do |f| %>
  #                  <%= item_form.file_field :poster %>
  #              <% end %>


  # Rails validations
  validates :title, :presence => true
  validates :title_original, :presence => true
  validates :description, :presence => true
  validates :year, :presence => true

  def get_persons(role)
    return Person.all #where(:role => role) #Person.where(:role => role)
  end

end

app/models/person.rb
class Person
  include NoBrainer::Document

  field :name
  field :role
  field :photo

  belongs_to :item


end

app/models/poster.rb
class Poster
  include NoBrainer::Document

  field :src

  belongs_to :item
  
end

app/models/production.rb
class Production
  include NoBrainer::Document

  field :title

  belongs_to :item

  def all
      return Array('1', '2')
  end

end

app/models/release.rb
class Cast
  include NoBrainer::Document

  field :country
  field :date

  belongs_to :item

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # 
  # before_action :set_locale
  #
  # def set_locale
  #   I18n.locale = params[:locale] || I18n.default_locale
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  def new
    @item = Item.new
    #@persons = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  def edit
    @item = Item.find(params[:id])
    #@persons = Person.all
  end

  def create
    #render plain: params[:item].inspect
    @item = Item.new(params[:item])

    ## build a photo and pass it into a block to set other attributes
    #@item = Item.new(params[:item]) do |t|
    #  if params[:item][:poster]
    #    uploaded_io = params[:item][:poster]
    #    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    #      file.write(uploaded_io.tempfile)
    #    end
    #    #t.poster    = params[:item][:poster].read
    #    #t.poster  = 'test'# uploaded_io.original_filename
    #    #t.mime_type = params[:item][:poster].content_type
    #  end
    #end
    #@item.poster = "http://ia.media-imdb.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SY317_CR1,0,214,317_AL_.jpg"
    #@item.poster = params[:item][:poster].original_filename
    ##@item.poster = Rails.root.join('public', 'uploads', params[:item][:poster].original_filename)
    ##http://ia.media-imdb.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SY317_CR1,0,214,317_AL_.jpg
    #

    respond_to do |format|
      if @item.save
        #format.html { redirect_to @item, notice: 'Элемент обновлен.' }
        format.html { redirect_to edit_item_url(@item), notice: 'Элемент обновлен.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @item = Item.find(params[:id])

    #@item.persons = self.filter_persons(params[:persons])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        #format.html { redirect_to @item, notice: 'Элемент обновлен.' }
        format.html { redirect_to edit_item_url(@item), notice: 'Элемент обновлен.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def filter_persons(persons)

    @filtered = persons.each do |p|
      if p != ''
        return p
      end
    end

    return @filtered
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
end

app/controllers/technology_controller.rb
class TechnologyController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/productions_helper.rb
module ProductionsHelper
end

app/helpers/technology_helper.rb
module TechnologyHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |item_form| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, 'error') %> prohibited this item from being saved.</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= item_form.label :title %><br />
    <%= item_form.text_field :title %>
  </div>

  <div class="field">
    <%= item_form.label :title_original %><br />
    <%= item_form.text_field :title_original %>
  </div>

  <div class="field">
    <%= item_form.label :year %><br />
    <%= item_form.text_field :year %>
  </div>


  <div class="field">
    <%= item_form.label :description %><br />
    <%= item_form.text_area :description %>
  </div>

  <div class="field">
    <%= item_form.label :countries %><br />
    <%= item_form.country_select :countries, ["United States", "Great Britain", "France", "Germany"] %>
  </div>

  <div class="actions">
    <%= item_form.submit %>
  </div>
<% end %>

app/views/items/_form2.html.erb
<%= simple_form_for @item, :html=> {:multipart=>true} do |item_form| %>

    <dl class="accordion" data-accordion>
        <dd>
            <a href="#panel1">Основная информация</a>
            <div id="panel1" class="content active">
                <%= item_form.input :poster, label: 'URL постера' %>
                <%= item_form.input :bg_image, label: 'Кадр для фона' %>
                <%= item_form.input :title, label: 'Название фильма' %>
                <%= item_form.input :title_original, label: 'Название в оригинале' %>
                <%= item_form.input :year, label: 'Год выхода', :as => :integer %>
                <%= item_form.country_select :countries, ["United States", "Great Britain", "France", "Germany"] , label: 'Страны' %>
                <%= item_form.text_area :description, label: 'Описание', input_html: { class: 'six columns' }, rows: 10 %>
            </div>
        </dd>

        <dd>
            <a href="#panel2">Люди</a>
            <div id="panel2" class="content">
                <dl class="tabs" data-tab>
                    <dd class="active"><a href="#panel2-1">Актеры</a></dd>
                    <dd><a href="#panel2-2">Режиссеры</a></dd>
                    <dd><a href="#panel2-3">Сценаристы</a></dd>
                    <dd><a href="#panel2-4">Продюссеры</a></dd>
                </dl>
                <div class="tabs-content">
                    <div class="content active" id="panel2-1">
                        <div class="row">
                            <div class="large-5 columns">
                                <label>Персона
                                    <input type="text" placeholder="введите имя" />
                                </label>
                            </div>
                            <div class="large-1 columns">
                                <br /><span>играл</span>
                            </div>
                            <div class="large-6 columns">
                                <label>Герой
                                    <input type="text" placeholder="имя персонажа" />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="content" id="panel2-2">
                        <div class="row">
                            <div class="large-6 columns">
                                <label>Персона
                                    <input type="text" placeholder="введите имя" />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="content" id="panel2-3">
                        <div class="row">
                            <div class="large-6 columns">
                                <label>Персона
                                    <input type="text" placeholder="введите имя" />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="content" id="panel2-4">
                        <div class="row">
                            <div class="large-6 columns">
                                <label>Персона
                                    <input type="text" placeholder="введите имя" />
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </dd>

        <dd>
            <a href="#panel3">Студии</a>
            <div id="panel3" class="content">
                <dl class="tabs" data-tab>
                    <dd class="active"><a href="#panel3-1">Производство</a></dd>
                    <dd><a href="#panel3-2">Прокат</a></dd>
                </dl>
                <div class="tabs-content">
                    <div class="content active" id="panel3-1">
                        <div class="large-12 columns">
                            <label>Студии производства
                                <select multiple="true" style="height: 150px;">
                                    <option value="marvel">Marvel Entertainment</option>
                                    <option value="disney">Walt Disney Studios Motion Pictures</option>
                                    <option value="fox">Twentieth Century Fox Film Corporation</option>
                                    <option value="dune">Dune Entertainment</option>
                                    <option value="hat">Bad Hat Harry Productionsn</option>
                                    <option value="screen">Big Screen Productions</option>
                                    <option value="warner">Warner Bros.</option>
                                </select>
                            </label>
                        </div>
                    </div>
                    <div class="content" id="panel3-2">
                        <div class="large-12 columns">
                            <label>Студии прокатчики
                                <select multiple="true" style="height: 150px;">
                                    <option value="marvel">Marvel Entertainment</option>
                                    <option value="disney">Walt Disney Studios Motion Pictures</option>
                                    <option value="fox">Twentieth Century Fox Film Corporation</option>
                                    <option value="dune">Dune Entertainment</option>
                                    <option value="hat">Bad Hat Harry Productionsn</option>
                                    <option value="screen">Big Screen Productions</option>
                                    <option value="warner">Warner Bros.</option>
                                </select>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </dd>

    </dl>

    <br />
    <p>
        <%= item_form.button :submit, label: 'Сохранить', class: 'success button' %>
        <% if @item.title %>
            <%= link_to 'Удалить', @item, method: :delete, data: { confirm: 'Вы уверены?' }, class: '[success alert secondary] [round radius] button' %>
        <% end %>
    </p>

<% end %>

app/views/items/_show.html.erb
<div class="panel callout radius">
<h3><%= @item.title %></h3>
<h5><%= @item.title_original %></h5>
<% if @item.poster != '' %>
    <a class="th [radius]" href="#">
        <img src="<%= @item.poster %>">
    </a>
<% end %>
<p>
    <%= @item.description %>
</p>
</div>

app/views/items/edit.html.erb
<h1>Редактирование</h1>

<div class="large-8 columns">
    <%= render 'form2' %>
</div>
<div class="large-4 columns">
    <%= render 'show' %>
</div>

app/views/items/index.html.erb
<ul class="small-block-grid-3">
    <% @items.each do |item| %>
        <li>
            <% if item.poster == '' %>
                <% item.poster = 'http://ia.media-imdb.com/images/G/01/imdb/images/nopicture/large/film-184890147._V379391879_.png' %>
            <% end %>
            <i class="fi-[icon]"></i>
            <% if item.poster != '' %>
                <a class="th [radius]" href="<%= url_for edit_item_path(item) %>">
                    <img src="<%= item.poster %>">
                </a>
            <% end %><br />
            <%= link_to item.title, edit_item_path(item) %><br />
            <%= link_to 'Удалить', item, method: :delete, data: { confirm: 'Вы уверены?' }, class: '[success alert secondary] [round radius] label' %>
        </li>
    <% end %>
</ul>

<ul class="pagination">
    <li class="arrow unavailable"><a href="">&laquo;</a></li>
    <li class="current"><a href="">1</a></li>
    <li><a href="">2</a></li>
    <li><a href="">3</a></li>
    <li><a href="">4</a></li>
    <li class="unavailable"><a href="">&hellip;</a></li>
    <li><a href="">12</a></li>
    <li><a href="">13</a></li>
    <li class="arrow"><a href="">&raquo;</a></li>
</ul>

app/views/items/new.html.erb
<h1>Новый элемент</h1>

<%= render 'form2' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div id="body">
    <h1><%= link_to @item.title, @item, :rel => "permalink" %></a></h1>
    <h2><%= @item.title_original %></h2>
    <% if @item.poster != '' %>
        <a class="th [radius]" href="#">
            <img src="<%= @item.poster %>">
        </a>
    <% end %>
    <div id="entry">
    <%= @item.description %>
    </div>
</div>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>