config/routes.rb
Rethinkfilms::Application.routes.draw do
  resources :companies

  resources :people

  resources :distributors

  resources :productions

  get "technology/index"
  resources :items

  root :to => "items#index"

end

app/models/cast.rb
class Cast
  include NoBrainer::Document

  field :name
  field :character
  field :picture

  belongs_to :item

end

app/models/company.rb
class Company
  include NoBrainer::Document

  belongs_to :item

end

app/models/director.rb
class Director
  include NoBrainer::Document

  field :name

end

app/models/distributor.rb
class Distributor
  # To change this template use File | Settings | File Templates.
end

app/models/item.rb
class Item
  include NoBrainer::Document

  # Defines the fields of the document visible to the application
  field :title
  field :title_original
  field :type, :default => "film"
  field :description
  field :year
  field :poster
  field :bg_image
  field :countries #, :type => Array
  field :persons
  field :companies

  #has_many :releases
  #has_many :poster
  has_many :persons
  #has_many :companies

  #serialize :persons, Array

  #<a class="th [radius]" href="#">
  #<img src="http://ia.media-imdb.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SY317_CR1,0,214,317_AL_.jpg">
  #</a>
  #              <%= form_for @item do |f| %>
  #                  <%= item_form.file_field :poster %>
  #              <% end %>


  # Rails validations
  validates :title, :presence => true
  validates :title_original, :presence => true
  validates :description, :presence => true
  validates :year, :presence => true

  def get_persons(role)
    return Person.all #where(:role => role) #Person.where(:role => role)
  end

end

app/models/person.rb
class Person
  include NoBrainer::Document

  field :name
  field :role
  field :photo

  belongs_to :item


end

app/models/poster.rb
class Poster
  include NoBrainer::Document

  field :src

  belongs_to :item
  
end

app/models/production.rb
class Production
  include NoBrainer::Document

  field :title

  belongs_to :item

  def all
      return Array('1', '2')
  end

end

app/models/release.rb
class Cast
  include NoBrainer::Document

  field :country
  field :date

  belongs_to :item

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  def new
    @item = Item.new
    #@persons = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  def edit
    @item = Item.find(params[:id])
    #@persons = Person.all
  end

  def create
    #render plain: params[:item].inspect
    @item = Item.new(params[:item])

    ## build a photo and pass it into a block to set other attributes
    #@item = Item.new(params[:item]) do |t|
    #  if params[:item][:poster]
    #    uploaded_io = params[:item][:poster]
    #    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    #      file.write(uploaded_io.tempfile)
    #    end
    #    #t.poster    = params[:item][:poster].read
    #    #t.poster  = 'test'# uploaded_io.original_filename
    #    #t.mime_type = params[:item][:poster].content_type
    #  end
    #end
    #@item.poster = "http://ia.media-imdb.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SY317_CR1,0,214,317_AL_.jpg"
    #@item.poster = params[:item][:poster].original_filename
    ##@item.poster = Rails.root.join('public', 'uploads', params[:item][:poster].original_filename)
    ##http://ia.media-imdb.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SY317_CR1,0,214,317_AL_.jpg
    #

    respond_to do |format|
      if @item.save
        #format.html { redirect_to @item, notice: 'Элемент обновлен.' }
        format.html { redirect_to edit_item_url(@item), notice: 'Элемент обновлен.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @item = Item.find(params[:id])

    #@item.persons = self.filter_persons(params[:persons])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        #format.html { redirect_to @item, notice: 'Элемент обновлен.' }
        format.html { redirect_to edit_item_url(@item), notice: 'Элемент обновлен.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def filter_persons(persons)

    @filtered = persons.each do |p|
      if p != ''
        return p
      end
    end

    return @filtered
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/productions_helper.rb
module ProductionsHelper
end

app/helpers/technology_helper.rb
module TechnologyHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "RethinkFilms - управление контентом" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <div class="contain-to-grid sticky">
          <nav class="top-bar" data-topbar data-options="sticky_on: large">
              <ul class="title-area">
                  <li class="name">
                      <h1><%= link_to "RethinkFilms - управление контентом", items_path %></a></h1>
                  </li>
              </ul>
              <section class="top-bar-section">
                  <ul class="left">
                      <li class="divider"></li>
                      <li><%= link_to "Список фильмов", items_path %></li>
                      <li class="divider"></li>
                      <li><%= link_to "Добавить элемент", new_item_path, class: 'button' %></li>
                      <li class="divider"></li>
                      <li class="has-form"><%= link_to "Технологии", controller: "technology", action: "index" %></li>
                      <li class="divider"></li>
                      <li class="has-form">
                          <div class="row collapse">
                              <div class="large-8 small-9 columns">
                                  <input type="text" placeholder="Поиск">
                              </div>
                              <div class="large-4 small-3 columns">
                                  <a href="#" class="alert button expand">Найти</a>
                              </div>
                          </div>
                      </li>
                  </ul>
              </section>
          </nav>
      </div>
      <div class="row">
          <br />
          <%= yield %>
      </div>

  <%= javascript_include_tag "application" %>
  </body>
</html>